# verifier

server:
  host: localhost
  port: 8080
  jwt_secret: myjwtsecretphrase
  database:
    dsn: postgres://myuser:mypassword@localhost:5432/vultisig-verifier?sslmode=disable
  vaults_file_path: /tmp/verifier/vaults
  mode: verifier
  plugin:
    type: dca
  user_auth:
    jwt_secret: tokensecret

plugin:
  plugin_configs:
    dca:
      rpc_url: https://eth.llamarpc.com
      uniswap:
        v2_router: 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D
        deadline: 5 # minutes

relay:
  server: https://api.vultisig.com/router

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

block_storage:
  type: s3
  endpoint: http://localhost:9000
  bucket: vultisig-verifier
  access_key: minioadmin
  secret: minioadmin
  region: us-east-1
  host: http://localhost:9000
  force_path_style: true
  disable_ssl: true

email_server:
  api_key: key-1234567890

datadog:
  host: localhost
  port: 8125
