# fly.toml app configuration file generated for verifier-server-dev on 2025-09-07T06:02:26+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'verifier-server-dev'
primary_region = 'nrt'

[build]
  [build.args]
    GO_VERSION = '1.24.2'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
