// @generated by protoc-gen-es v2.6.2 with parameter "target=ts"
// @generated from file recipe_specification.proto (package types, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ConstraintType } from "./constraint_pb";
import { file_constraint } from "./constraint_pb";
import { file_google_protobuf_struct } from "@bufbuild/protobuf/wkt";
import type { ResourcePath } from "./resource_pb";
import { file_resource } from "./resource_pb";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file recipe_specification.proto.
 */
export const file_recipe_specification: GenFile = /*@__PURE__*/
  fileDesc("ChpyZWNpcGVfc3BlY2lmaWNhdGlvbi5wcm90bxIFdHlwZXMijwIKDFJlY2lwZVNjaGVtYRIPCgd2ZXJzaW9uGAEgASgFEhgKEHNjaGVkdWxlX3ZlcnNpb24YAiABKAUSEQoJcGx1Z2luX2lkGAMgASgJEhMKC3BsdWdpbl9uYW1lGAQgASgJEhYKDnBsdWdpbl92ZXJzaW9uGAUgASgFEjMKE3N1cHBvcnRlZF9yZXNvdXJjZXMYBiADKAsyFi50eXBlcy5SZXNvdXJjZVBhdHRlcm4SLwoMcmVxdWlyZW1lbnRzGAggASgLMhkudHlwZXMuUGx1Z2luUmVxdWlyZW1lbnRzEi4KDWNvbmZpZ3VyYXRpb24YCSABKAsyFy5nb29nbGUucHJvdG9idWYuU3RydWN0IpUBCg9SZXNvdXJjZVBhdHRlcm4SKgoNcmVzb3VyY2VfcGF0aBgBIAEoCzITLnR5cGVzLlJlc291cmNlUGF0aBJEChZwYXJhbWV0ZXJfY2FwYWJpbGl0aWVzGAIgAygLMiQudHlwZXMuUGFyYW1ldGVyQ29uc3RyYWludENhcGFiaWxpdHkSEAoIcmVxdWlyZWQYAyABKAgieQodUGFyYW1ldGVyQ29uc3RyYWludENhcGFiaWxpdHkSFgoOcGFyYW1ldGVyX25hbWUYASABKAkSLgoPc3VwcG9ydGVkX3R5cGVzGAIgAygOMhUudHlwZXMuQ29uc3RyYWludFR5cGUSEAoIcmVxdWlyZWQYAyABKAgiTAoSUGx1Z2luUmVxdWlyZW1lbnRzEhwKFG1pbl92dWx0aXNpZ192ZXJzaW9uGAEgASgFEhgKEHN1cHBvcnRlZF9jaGFpbnMYAiADKAlCI1ohZ2l0aHViLmNvbS92dWx0aXNpZy9yZWNpcGVzL3R5cGVzYgZwcm90bzM", [file_constraint, file_google_protobuf_struct, file_resource]);

/**
 * RecipeSchema defines what types of recipes/policies a plugin can handle
 * This is used for UI filtering and policy validation
 *
 * @generated from message types.RecipeSchema
 */
export type RecipeSchema = Message<"types.RecipeSchema"> & {
  /**
   * Schema version for future compatibility
   *
   * @generated from field: int32 version = 1;
   */
  version: number;

  /**
   * Scheduling specification version this plugin supports
   *
   * @generated from field: int32 schedule_version = 2;
   */
  scheduleVersion: number;

  /**
   * Plugin identification
   *
   * @generated from field: string plugin_id = 3;
   */
  pluginId: string;

  /**
   * @generated from field: string plugin_name = 4;
   */
  pluginName: string;

  /**
   * @generated from field: int32 plugin_version = 5;
   */
  pluginVersion: number;

  /**
   * What resources this plugin can handle with their parameter constraints
   *
   * @generated from field: repeated types.ResourcePattern supported_resources = 6;
   */
  supportedResources: ResourcePattern[];

  /**
   * Plugin requirements
   *
   * @generated from field: types.PluginRequirements requirements = 8;
   */
  requirements?: PluginRequirements;

  /**
   * Plugin configuration
   *
   * @generated from field: google.protobuf.Struct configuration = 9;
   */
  configuration?: JsonObject;
};

/**
 * Describes the message types.RecipeSchema.
 * Use `create(RecipeSchemaSchema)` to create a new message.
 */
export const RecipeSchemaSchema: GenMessage<RecipeSchema> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 0);

/**
 * ResourcePattern defines a specific resource and what constraints its parameters support
 *
 * @generated from message types.ResourcePattern
 */
export type ResourcePattern = Message<"types.ResourcePattern"> & {
  /**
   * Specific resource (e.g., ethereum.eth.transfer)
   *
   * @generated from field: types.ResourcePath resource_path = 1;
   */
  resourcePath?: ResourcePath;

  /**
   * What constraint types each parameter of this resource supports
   *
   * @generated from field: repeated types.ParameterConstraintCapability parameter_capabilities = 2;
   */
  parameterCapabilities: ParameterConstraintCapability[];

  /**
   * Whether this resource is required by the plugin
   *
   * @generated from field: bool required = 3;
   */
  required: boolean;
};

/**
 * Describes the message types.ResourcePattern.
 * Use `create(ResourcePatternSchema)` to create a new message.
 */
export const ResourcePatternSchema: GenMessage<ResourcePattern> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 1);

/**
 * ParameterConstraintCapability defines what constraint types a parameter supports
 *
 * @generated from message types.ParameterConstraintCapability
 */
export type ParameterConstraintCapability = Message<"types.ParameterConstraintCapability"> & {
  /**
   * Parameter name (e.g., "recipient", "amount")
   *
   * @generated from field: string parameter_name = 1;
   */
  parameterName: string;

  /**
   * Supported constraint types for this parameter
   *
   * @generated from field: repeated types.ConstraintType supported_types = 2;
   */
  supportedTypes: ConstraintType[];

  /**
   * Whether this parameter must be constrained
   *
   * @generated from field: bool required = 3;
   */
  required: boolean;
};

/**
 * Describes the message types.ParameterConstraintCapability.
 * Use `create(ParameterConstraintCapabilitySchema)` to create a new message.
 */
export const ParameterConstraintCapabilitySchema: GenMessage<ParameterConstraintCapability> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 2);

/**
 * PluginRequirements defines what the plugin needs to function
 *
 * @generated from message types.PluginRequirements
 */
export type PluginRequirements = Message<"types.PluginRequirements"> & {
  /**
   * Minimum Vultisig version required
   *
   * @generated from field: int32 min_vultisig_version = 1;
   */
  minVultisigVersion: number;

  /**
   * Supported blockchain networks
   *
   * @generated from field: repeated string supported_chains = 2;
   */
  supportedChains: string[];
};

/**
 * Describes the message types.PluginRequirements.
 * Use `create(PluginRequirementsSchema)` to create a new message.
 */
export const PluginRequirementsSchema: GenMessage<PluginRequirements> = /*@__PURE__*/
  messageDesc(file_recipe_specification, 3);

