// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: control_flags.sql

package queries

import (
	"context"
)

const getControlFlag = `-- name: GetControlFlag :one

SELECT key, enabled, updated_at FROM control_flags
WHERE key = $1
`

// Control Flags table queries (kill switch functionality)
func (q *Queries) GetControlFlag(ctx context.Context, key string) (*ControlFlag, error) {
	row := q.db.QueryRow(ctx, getControlFlag, key)
	var i ControlFlag
	err := row.Scan(&i.Key, &i.Enabled, &i.UpdatedAt)
	return &i, err
}

const getControlFlagsByKeys = `-- name: GetControlFlagsByKeys :many
SELECT key, enabled, updated_at FROM control_flags
WHERE key = ANY($1::text[])
`

func (q *Queries) GetControlFlagsByKeys(ctx context.Context, dollar_1 []string) ([]*ControlFlag, error) {
	rows, err := q.db.Query(ctx, getControlFlagsByKeys, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ControlFlag{}
	for rows.Next() {
		var i ControlFlag
		if err := rows.Scan(&i.Key, &i.Enabled, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertControlFlag = `-- name: UpsertControlFlag :exec
INSERT INTO control_flags (key, enabled, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE
SET enabled = EXCLUDED.enabled, updated_at = NOW()
`

type UpsertControlFlagParams struct {
	Key     string `json:"key"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpsertControlFlag(ctx context.Context, arg *UpsertControlFlagParams) error {
	_, err := q.db.Exec(ctx, upsertControlFlag, arg.Key, arg.Enabled)
	return err
}

const upsertControlFlagReturning = `-- name: UpsertControlFlagReturning :one
INSERT INTO control_flags (key, enabled, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE
SET enabled = EXCLUDED.enabled, updated_at = NOW()
RETURNING key, enabled, updated_at
`

type UpsertControlFlagReturningParams struct {
	Key     string `json:"key"`
	Enabled bool   `json:"enabled"`
}

func (q *Queries) UpsertControlFlagReturning(ctx context.Context, arg *UpsertControlFlagReturningParams) (*ControlFlag, error) {
	row := q.db.QueryRow(ctx, upsertControlFlagReturning, arg.Key, arg.Enabled)
	var i ControlFlag
	err := row.Scan(&i.Key, &i.Enabled, &i.UpdatedAt)
	return &i, err
}
