// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package queries

import (
	"context"
)

const getPluginByID = `-- name: GetPluginByID :one

SELECT id, title, description, server_endpoint, category, created_at, updated_at, faqs, features, audited FROM plugins
WHERE id = $1
`

// Plugins table queries
func (q *Queries) GetPluginByID(ctx context.Context, id string) (*Plugin, error) {
	row := q.db.QueryRow(ctx, getPluginByID, id)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServerEndpoint,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Faqs,
		&i.Features,
		&i.Audited,
	)
	return &i, err
}

const getPluginByIDAndOwner = `-- name: GetPluginByIDAndOwner :one
SELECT p.id, p.title, p.description, p.server_endpoint, p.category, p.created_at, p.updated_at, p.faqs, p.features, p.audited FROM plugins p
JOIN plugin_owners po ON p.id = po.plugin_id
WHERE p.id = $1 AND po.public_key = $2 AND po.active = true
`

type GetPluginByIDAndOwnerParams struct {
	ID        string `json:"id"`
	PublicKey string `json:"public_key"`
}

func (q *Queries) GetPluginByIDAndOwner(ctx context.Context, arg *GetPluginByIDAndOwnerParams) (*Plugin, error) {
	row := q.db.QueryRow(ctx, getPluginByIDAndOwner, arg.ID, arg.PublicKey)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServerEndpoint,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Faqs,
		&i.Features,
		&i.Audited,
	)
	return &i, err
}

const getPluginPricings = `-- name: GetPluginPricings :many
SELECT id, type, frequency, amount, asset, metric, plugin_id, created_at, updated_at FROM pricings
WHERE plugin_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetPluginPricings(ctx context.Context, pluginID string) ([]*Pricing, error) {
	rows, err := q.db.Query(ctx, getPluginPricings, pluginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Pricing{}
	for rows.Next() {
		var i Pricing
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Frequency,
			&i.Amount,
			&i.Asset,
			&i.Metric,
			&i.PluginID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlugins = `-- name: ListPlugins :many
SELECT id, title, description, server_endpoint, category, created_at, updated_at, faqs, features, audited FROM plugins
ORDER BY updated_at DESC
`

func (q *Queries) ListPlugins(ctx context.Context) ([]*Plugin, error) {
	rows, err := q.db.Query(ctx, listPlugins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ServerEndpoint,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Faqs,
			&i.Features,
			&i.Audited,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginsByOwner = `-- name: ListPluginsByOwner :many
SELECT p.id, p.title, p.description, p.server_endpoint, p.category, p.created_at, p.updated_at, p.faqs, p.features, p.audited FROM plugins p
JOIN plugin_owners po ON p.id = po.plugin_id
WHERE po.public_key = $1 AND po.active = true
ORDER BY p.updated_at DESC
`

func (q *Queries) ListPluginsByOwner(ctx context.Context, publicKey string) ([]*Plugin, error) {
	rows, err := q.db.Query(ctx, listPluginsByOwner, publicKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Plugin{}
	for rows.Next() {
		var i Plugin
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ServerEndpoint,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Faqs,
			&i.Features,
			&i.Audited,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlugin = `-- name: UpdatePlugin :one
UPDATE plugins
SET
    title = $2,
    description = $3,
    server_endpoint = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, title, description, server_endpoint, category, created_at, updated_at, faqs, features, audited
`

type UpdatePluginParams struct {
	ID             string `json:"id"`
	Title          string `json:"title"`
	Description    string `json:"description"`
	ServerEndpoint string `json:"server_endpoint"`
}

func (q *Queries) UpdatePlugin(ctx context.Context, arg *UpdatePluginParams) (*Plugin, error) {
	row := q.db.QueryRow(ctx, updatePlugin,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ServerEndpoint,
	)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServerEndpoint,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Faqs,
		&i.Features,
		&i.Audited,
	)
	return &i, err
}
