// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: plugins.sql

package queries

import (
	"context"
)

const getPluginByID = `-- name: GetPluginByID :one
SELECT id, title, description, server_endpoint, category, created_at, updated_at, logo_url, thumbnail_url, images, faqs, features, audited FROM plugins
WHERE id = $1
`

func (q *Queries) GetPluginByID(ctx context.Context, id PluginID) (*Plugin, error) {
	row := q.db.QueryRow(ctx, getPluginByID, id)
	var i Plugin
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ServerEndpoint,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.ThumbnailUrl,
		&i.Images,
		&i.Faqs,
		&i.Features,
		&i.Audited,
	)
	return &i, err
}
