// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: portal_approvers.sql

package queries

import (
	"context"
)

const getPortalApprover = `-- name: GetPortalApprover :one

SELECT public_key, role, active, added_via, added_by_public_key, created_at, updated_at FROM portal_approvers WHERE public_key = $1
`

// Portal Approvers table queries
func (q *Queries) GetPortalApprover(ctx context.Context, publicKey string) (*PortalApprover, error) {
	row := q.db.QueryRow(ctx, getPortalApprover, publicKey)
	var i PortalApprover
	err := row.Scan(
		&i.PublicKey,
		&i.Role,
		&i.Active,
		&i.AddedVia,
		&i.AddedByPublicKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const isListingApprover = `-- name: IsListingApprover :one
SELECT EXISTS(
  SELECT 1 FROM portal_approvers
  WHERE public_key = $1
    AND active = TRUE
    AND role IN ('listing_approver', 'admin')
) AS is_approver
`

func (q *Queries) IsListingApprover(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRow(ctx, isListingApprover, publicKey)
	var is_approver bool
	err := row.Scan(&is_approver)
	return is_approver, err
}

const isPortalAdmin = `-- name: IsPortalAdmin :one
SELECT EXISTS(
  SELECT 1 FROM portal_approvers
  WHERE public_key = $1
    AND active = TRUE
    AND role = 'admin'
) AS is_admin
`

func (q *Queries) IsPortalAdmin(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRow(ctx, isPortalAdmin, publicKey)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const isStagingApprover = `-- name: IsStagingApprover :one
SELECT EXISTS(
  SELECT 1 FROM portal_approvers
  WHERE public_key = $1
    AND active = TRUE
    AND role IN ('staging_approver', 'listing_approver', 'admin')
) AS is_approver
`

func (q *Queries) IsStagingApprover(ctx context.Context, publicKey string) (bool, error) {
	row := q.db.QueryRow(ctx, isStagingApprover, publicKey)
	var is_approver bool
	err := row.Scan(&is_approver)
	return is_approver, err
}
