// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://todo.com",
        "contact": {
            "name": "API Support",
            "url": "http://todo.com",
            "email": "todo@todo.com"
        },
        "license": {
            "name": "MIT Licence",
            "url": "https://raw.githubusercontent.com/vultisig/verifier/refs/heads/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "todo.com",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Vultisig Verifier API",
	Description:      "The Verifier (trusted counterparty) API for Vultisig plugins.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
